services:
  # --- Base de Données (Postgres) ---
  db:
    image: postgres:15
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pos_network

  # --- Backend Laravel (PHP-FPM) ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    env_file: .env
    networks:
      - pos_network

  # --- Serveur Web (Nginx) ---
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - pos_network

  # --- Frontend (Vue.js / Vite) ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - nginx
    env_file:
      - ./frontend/.env
    networks:
      - pos_network

  # --- Jenkins (CI/CD Automation) ---
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    privileged: true
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - pos_network

networks:
  pos_network:
    driver: bridge

volumes:
  postgres_data:
  jenkins_data: